name: bai
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bleach=3.2.3
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - cairo=1.14.12
  - certifi=2020.6.20
  - cloudpickle=1.6.0
  - cycler=0.10.0
  - dask-core=2.6.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.2.3
  - expat=2.2.10
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.63.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.9.0
  - intel-openmp=2019.4
  - ipykernel=4.10.0
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - jasper=2.0.14
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=5.2.0
  - jupyter_core=4.5.0
  - kiwisolver=1.0.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.0
  - matplotlib=3.0.0
  - mistune=0.8.3
  - mkl=2018.0.3
  - nbconvert=5.5.0
  - nbformat=5.1.2
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.8.2
  - notebook=5.6.0
  - numpy=1.14.2
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.0.2u
  - packaging=20.8
  - pandoc=2.11
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=5.2.0
  - pip=10.0.1
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.7.0
  - py-opencv=3.4.2
  - pygments=2.7.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.5.6
  - python-dateutil=2.8.1
  - pytorch=1.5.1
  - pytz=2020.5
  - pywavelets=1.0.0
  - pyzmq=17.1.2
  - qt=5.9.6
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=7.0
  - scikit-image=0.14.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.1
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.11.1
  - torchaudio=0.5.1
  - torchvision=0.6.1
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.4.1
  - xz=5.2.5
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - chardet==4.0.0
    - click==7.1.2
    - configparser==4.0.2
    - docker-pycreds==0.4.0
    - gitdb==4.0.5
    - gitpython==3.1.12
    - idna==2.10
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.8.0
    - pyyaml==5.3.1
    - requests==2.25.1
    - sentry-sdk==0.19.5
    - shortuuid==1.0.1
    - smmap==3.0.5
    - subprocess32==3.5.4
    - tqdm==4.56.0
    - urllib3==1.26.3
    - wandb==0.10.15
    - watchdog==0.10.4


